#baseurl: ""
#url: ""
title: u8sand.net
subtitle: an online profile for Daniel J. B. Clarke
description: >
  TODO
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: _sass
