#baseurl: ""
#url: ""
title: Daniel J. B. Clarke
subtitle: an online curriculum vitae
description: >
  Daniel J. B. Clarke, is an open source programmer and data science researcher interested in AI and involved in bioinformatics.
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: _sass
